/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BienfaitsRouteImport } from './routes/bienfaits'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as EscaladesRouteImport } from './routes/escalades'
import { Route as FacturesRouteImport } from './routes/factures'
import { Route as MessageAccueilRouteImport } from './routes/message-accueil'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as ConversationsIndexRouteImport } from './routes/conversations.index'
import { Route as ConversationsPhoneRouteImport } from './routes/conversations.$phone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BienfaitsRoute = BienfaitsRouteImport.update({
  id: '/bienfaits',
  path: '/bienfaits',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const EscaladesRoute = EscaladesRouteImport.update({
  id: '/escalades',
  path: '/escalades',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesRoute = FacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageAccueilRoute = MessageAccueilRouteImport.update({
  id: '/message-accueil',
  path: '/message-accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConversationsRoute,
} as any)
const ConversationsPhoneRoute = ConversationsPhoneRouteImport.update({
  id: '/$phone',
  path: '/$phone',
  getParentRoute: () => ConversationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienfaits': typeof BienfaitsRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/escalades': typeof EscaladesRoute
  '/factures': typeof FacturesRoute
  '/message-accueil': typeof MessageAccueilRoute
  '/paiement': typeof PaiementRoute
  '/procedures': typeof ProceduresRoute
  '/conversations/$phone': typeof ConversationsPhoneRoute
  '/conversations/': typeof ConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienfaits': typeof BienfaitsRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/escalades': typeof EscaladesRoute
  '/factures': typeof FacturesRoute
  '/message-accueil': typeof MessageAccueilRoute
  '/paiement': typeof PaiementRoute
  '/procedures': typeof ProceduresRoute
  '/conversations/$phone': typeof ConversationsPhoneRoute
  '/conversations': typeof ConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bienfaits': typeof BienfaitsRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/escalades': typeof EscaladesRoute
  '/factures': typeof FacturesRoute
  '/message-accueil': typeof MessageAccueilRoute
  '/paiement': typeof PaiementRoute
  '/procedures': typeof ProceduresRoute
  '/conversations/$phone': typeof ConversationsPhoneRoute
  '/conversations/': typeof ConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienfaits'
    | '/catalogue'
    | '/chat'
    | '/conversations'
    | '/escalades'
    | '/factures'
    | '/message-accueil'
    | '/paiement'
    | '/procedures'
    | '/conversations/$phone'
    | '/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienfaits'
    | '/catalogue'
    | '/chat'
    | '/escalades'
    | '/factures'
    | '/message-accueil'
    | '/paiement'
    | '/procedures'
    | '/conversations/$phone'
    | '/conversations'
  id:
    | '__root__'
    | '/'
    | '/bienfaits'
    | '/catalogue'
    | '/chat'
    | '/conversations'
    | '/escalades'
    | '/factures'
    | '/message-accueil'
    | '/paiement'
    | '/procedures'
    | '/conversations/$phone'
    | '/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BienfaitsRoute: typeof BienfaitsRoute
  CatalogueRoute: typeof CatalogueRoute
  ChatRoute: typeof ChatRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  EscaladesRoute: typeof EscaladesRoute
  FacturesRoute: typeof FacturesRoute
  MessageAccueilRoute: typeof MessageAccueilRoute
  PaiementRoute: typeof PaiementRoute
  ProceduresRoute: typeof ProceduresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienfaits': {
      id: '/bienfaits'
      path: '/bienfaits'
      fullPath: '/bienfaits'
      preLoaderRoute: typeof BienfaitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalades': {
      id: '/escalades'
      path: '/escalades'
      fullPath: '/escalades'
      preLoaderRoute: typeof EscaladesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures': {
      id: '/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof FacturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message-accueil': {
      id: '/message-accueil'
      path: '/message-accueil'
      fullPath: '/message-accueil'
      preLoaderRoute: typeof MessageAccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/conversations/$phone': {
      id: '/conversations/$phone'
      path: '/$phone'
      fullPath: '/conversations/$phone'
      preLoaderRoute: typeof ConversationsPhoneRouteImport
      parentRoute: typeof ConversationsRoute
    }
  }
}

interface ConversationsRouteChildren {
  ConversationsPhoneRoute: typeof ConversationsPhoneRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsPhoneRoute: ConversationsPhoneRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BienfaitsRoute: BienfaitsRoute,
  CatalogueRoute: CatalogueRoute,
  ChatRoute: ChatRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  EscaladesRoute: EscaladesRoute,
  FacturesRoute: FacturesRoute,
  MessageAccueilRoute: MessageAccueilRoute,
  PaiementRoute: PaiementRoute,
  ProceduresRoute: ProceduresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
